# Generated by Django 3.0.8 on 2020-07-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservar',
            name='Devolver',
            field=models.DateField(),
        ),
    ]
